version: '3'

services:
  cep-retriever:
    #build: .
    image: allancordeiros/cep-retriever
    container_name: cep-retriever
    hostname: cep-retriever
    ports:
      - "8080:8080"
    networks:
      - cep-retriever

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - cep-retriever
  grafana-service:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    networks:
      - cep-retriever

networks:
  cep-retriever:
    driver: bridge
volumes:
  prometheus_data: {}