global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cep-retriever'
    static_configs:
      - targets: ["cep-retriever:8080"]
  - job_name: 'prometheus'
    static_configs:
      - targets: [ "prometheus:9090" ]
